boot_failures: 1

# BUG: KFENCE: out-of-bounds read in test_out_of_bounds_read
BUG:KFENCE:out-of-bounds_read_in_test_out_of_bounds_read: 1
message:BUG:KFENCE:out-of-bounds_read_in_test_out_of_bounds_read: BUG: KFENCE: out-of-bounds read in test_out_of_bounds_read+0xa6/0x234
pattern:BUG:KFENCE:out-of-bounds_read_in_test_out_of_bounds_read: BUG: KFENCE: out-of-bounds read in test_out_of_bounds_read

# BUG: KFENCE: use-after-free read in test_use_after_free_read
BUG:KFENCE:use-after-free_read_in_test_use_after_free_read: 1
message:BUG:KFENCE:use-after-free_read_in_test_use_after_free_read: BUG: KFENCE: use-after-free read in test_use_after_free_read+0xb3/0x143
pattern:BUG:KFENCE:use-after-free_read_in_test_use_after_free_read: BUG: KFENCE: use-after-free read in test_use_after_free_read

